<!-- filepath: d:\Repositories\Al-Emaan_Travels\vendor\artflow-studio\table\src\resources\views\exports\pdf.blade.php -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'Data Export' }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .export-info {
            margin-bottom: 20px;
            font-size: 10px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title ?? 'Data Export' }}</h1>
    </div>
    
    <div class="export-info">
        <p><strong>Exported on:</strong> {{ now()->format('F j, Y g:i A') }}</p>
        <p><strong>Total Records:</strong> {{ count($data) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $row)
                <tr>
                    @foreach ($columns as $column)
                        <td>
                            @if (isset($column['raw']))
                                {!! strip_tags($this->renderRawHtml($column['raw'], $row)) !!}
                            @elseif (isset($column['relation']))
                                @php [$relation, $attribute] = explode(':', $column['relation']); @endphp
                                {{ $row->$relation->$attribute ?? '' }}
                            @else
                                {{ $row->{$column['key']} ?? '' }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by AFTable Package</p>
    </div>
</body>
</html>
